// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package organizations

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// CreateOrgCreateOrganization includes the requested fields of the GraphQL type Organization.
type CreateOrgCreateOrganization struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns CreateOrgCreateOrganization.Id, and is useful for accessing the field via an interface.
func (v *CreateOrgCreateOrganization) GetId() string { return v.Id }

// GetName returns CreateOrgCreateOrganization.Name, and is useful for accessing the field via an interface.
func (v *CreateOrgCreateOrganization) GetName() string { return v.Name }

// CreateOrgResponse is returned by CreateOrg on success.
type CreateOrgResponse struct {
	CreateOrganization CreateOrgCreateOrganization `json:"createOrganization"`
}

// GetCreateOrganization returns CreateOrgResponse.CreateOrganization, and is useful for accessing the field via an interface.
func (v *CreateOrgResponse) GetCreateOrganization() CreateOrgCreateOrganization {
	return v.CreateOrganization
}

// GetOrganizationOrganization includes the requested fields of the GraphQL type Organization.
type GetOrganizationOrganization struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns GetOrganizationOrganization.Id, and is useful for accessing the field via an interface.
func (v *GetOrganizationOrganization) GetId() string { return v.Id }

// GetName returns GetOrganizationOrganization.Name, and is useful for accessing the field via an interface.
func (v *GetOrganizationOrganization) GetName() string { return v.Name }

// GetOrganizationResponse is returned by GetOrganization on success.
type GetOrganizationResponse struct {
	Organization GetOrganizationOrganization `json:"organization"`
}

// GetOrganization returns GetOrganizationResponse.Organization, and is useful for accessing the field via an interface.
func (v *GetOrganizationResponse) GetOrganization() GetOrganizationOrganization {
	return v.Organization
}

// ListOrganizationsOrganizationsOrganization includes the requested fields of the GraphQL type Organization.
type ListOrganizationsOrganizationsOrganization struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns ListOrganizationsOrganizationsOrganization.Id, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganization) GetId() string { return v.Id }

// GetName returns ListOrganizationsOrganizationsOrganization.Name, and is useful for accessing the field via an interface.
func (v *ListOrganizationsOrganizationsOrganization) GetName() string { return v.Name }

// ListOrganizationsResponse is returned by ListOrganizations on success.
type ListOrganizationsResponse struct {
	Organizations []ListOrganizationsOrganizationsOrganization `json:"organizations"`
}

// GetOrganizations returns ListOrganizationsResponse.Organizations, and is useful for accessing the field via an interface.
func (v *ListOrganizationsResponse) GetOrganizations() []ListOrganizationsOrganizationsOrganization {
	return v.Organizations
}

type OrganizationUpdate struct {
	Name     string `json:"name"`
	ImageURL string `json:"imageURL"`
}

// GetName returns OrganizationUpdate.Name, and is useful for accessing the field via an interface.
func (v *OrganizationUpdate) GetName() string { return v.Name }

// GetImageURL returns OrganizationUpdate.ImageURL, and is useful for accessing the field via an interface.
func (v *OrganizationUpdate) GetImageURL() string { return v.ImageURL }

// UpdateOrgResponse is returned by UpdateOrg on success.
type UpdateOrgResponse struct {
	UpdateOrganization UpdateOrgUpdateOrganization `json:"updateOrganization"`
}

// GetUpdateOrganization returns UpdateOrgResponse.UpdateOrganization, and is useful for accessing the field via an interface.
func (v *UpdateOrgResponse) GetUpdateOrganization() UpdateOrgUpdateOrganization {
	return v.UpdateOrganization
}

// UpdateOrgUpdateOrganization includes the requested fields of the GraphQL type Organization.
type UpdateOrgUpdateOrganization struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns UpdateOrgUpdateOrganization.Id, and is useful for accessing the field via an interface.
func (v *UpdateOrgUpdateOrganization) GetId() string { return v.Id }

// GetName returns UpdateOrgUpdateOrganization.Name, and is useful for accessing the field via an interface.
func (v *UpdateOrgUpdateOrganization) GetName() string { return v.Name }

// __GetOrganizationInput is used internally by genqlient
type __GetOrganizationInput struct {
	Id string `json:"id"`
}

// GetId returns __GetOrganizationInput.Id, and is useful for accessing the field via an interface.
func (v *__GetOrganizationInput) GetId() string { return v.Id }

// __UpdateOrgInput is used internally by genqlient
type __UpdateOrgInput struct {
	Id     string             `json:"id"`
	Update OrganizationUpdate `json:"update"`
}

// GetId returns __UpdateOrgInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateOrgInput) GetId() string { return v.Id }

// GetUpdate returns __UpdateOrgInput.Update, and is useful for accessing the field via an interface.
func (v *__UpdateOrgInput) GetUpdate() OrganizationUpdate { return v.Update }

func CreateOrg(
	ctx context.Context,
	client graphql.Client,
) (*CreateOrgResponse, error) {
	req := &graphql.Request{
		OpName: "CreateOrg",
		Query: `
mutation CreateOrg {
	createOrganization {
		id
		name
	}
}
`,
	}
	var err error

	var data CreateOrgResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetOrganization(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*GetOrganizationResponse, error) {
	req := &graphql.Request{
		OpName: "GetOrganization",
		Query: `
query GetOrganization ($id: ID!) {
	organization(id: $id) {
		id
		name
	}
}
`,
		Variables: &__GetOrganizationInput{
			Id: id,
		},
	}
	var err error

	var data GetOrganizationResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func ListOrganizations(
	ctx context.Context,
	client graphql.Client,
) (*ListOrganizationsResponse, error) {
	req := &graphql.Request{
		OpName: "ListOrganizations",
		Query: `
query ListOrganizations {
	organizations {
		id
		name
	}
}
`,
	}
	var err error

	var data ListOrganizationsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func UpdateOrg(
	ctx context.Context,
	client graphql.Client,
	id string,
	update OrganizationUpdate,
) (*UpdateOrgResponse, error) {
	req := &graphql.Request{
		OpName: "UpdateOrg",
		Query: `
mutation UpdateOrg ($id: ID!, $update: OrganizationUpdate!) {
	updateOrganization(id: $id, update: $update) {
		id
		name
	}
}
`,
		Variables: &__UpdateOrgInput{
			Id:     id,
			Update: update,
		},
	}
	var err error

	var data UpdateOrgResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
